server:
  port: 8099
spring:
  application:
    name: YPassport
  datasource:
    druid:
      url: jdbc:mysql://rm-2ze5zk0f4v56za64a3o.mysql.rds.aliyuncs.com:3306/hesuan2?characterEncoding=utf-8
      username: suxiang
      password: Su1584699582
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.mirac.main.ypassport.dao
  configuration:
    map-underscore-to-camel-case: true

ypassport:
  key:
    privateKeyPath: D:\Auserfile\program\rsa_key\rsa.pri
    publicKeyPath: D:\Auserfile\program\rsa_key\rsa.pub
    expire: 30
    cookieName: YP_TOKEN
